name: lovementor
version:
authors:
description: LoveMentor
homepage:
environment:
  sdk: ">=1.4.0"
dependencies:
  stream: any
dev_dependencies:
  unittest: any
transformers:
- $dart2js:
    checked: true
    minify: true